# -*- coding: utf-8 -*-

"""Shared output-token estimation for generated model responses."""

import json
from typing import Any, Dict, List

from kiro.tokenizer import count_tokens


def count_generated_output_tokens(
    content: str,
    thinking_content: str,
    tool_calls: List[Dict[str, Any]],
) -> int:
    """Count text, reasoning, and function-call output generated by a model.

    Kiro does not expose an exact output-token count, so all API adapters use
    the same tiktoken approximation. Function names and arguments are part of
    model output and must be included even when a response has no visible text.

    Args:
        content: Visible assistant text emitted to the client.
        thinking_content: Generated reasoning text tracked by the gateway.
        tool_calls: OpenAI-, Anthropic-, or Kiro-shaped function calls.

    Returns:
        Approximate token count for the complete generated output.
    """
    output_parts = [content, thinking_content]
    for tool_call in tool_calls:
        function = tool_call.get("function")
        if not isinstance(function, dict):
            function = tool_call

        name = function.get("name")
        output_parts.append(name if isinstance(name, str) else "")

        arguments = function.get("arguments")
        if arguments is None:
            arguments = tool_call.get("input")
        if isinstance(arguments, (dict, list)):
            try:
                arguments = json.dumps(arguments, ensure_ascii=False)
            except (TypeError, ValueError):
                arguments = "{}"
        elif not isinstance(arguments, str):
            arguments = "{}"
        if not arguments:
            arguments = "{}"
        output_parts.append(arguments)

    return count_tokens("".join(output_parts))
